import { db } from '../db/index.ts';
import { eventBus } from '../agents/eventBus.ts';
import type { CRMEvent } from '../agents/protocol.ts';
import { TaskService } from './TaskService.ts';
import { CommunicationService } from './CommunicationService.ts';
import { JobService } from './JobService.ts';
import type { AutomationRule } from '../types.ts';

export class AutomationService {
    static init() {
        eventBus.subscribe('orchestrator', ['*'], async (event: CRMEvent) => {
            AutomationService.processEvent(event);
        });
        console.log('[AutomationService] Initialized and listening to EventBus');
    }

    static processEvent(event: CRMEvent) {
        // Find matching active rules
        const rules = db.prepare('SELECT * FROM automation_rules WHERE triggerEvent = ? AND isActive = 1').all(event.type) as AutomationRule[];

        for (const rule of rules) {
            try {
                // Evaluate conditions
                const conditions = JSON.parse(rule.conditions || '[]');
                if (AutomationService.evaluateConditions(conditions, event.data)) {
                    // Execute actions
                    const actions = JSON.parse(rule.actions || '[]');
                    for (const action of actions) {
                        AutomationService.executeAction(rule.id, action, event);
                    }
                }
            } catch (err: any) {
                console.error(`[AutomationService] Rule ${rule.id} failed:`, err);
                AutomationService.logRun(rule.id, event.data, 'failed', err.message);
            }
        }
    }

    static evaluateConditions(conditions: any[], payload: any): boolean {
        // Evaluate simple conditions like { field: 'stage', op: 'eq', value: 'approved' }
        if (!conditions || conditions.length === 0) return true;

        for (const cond of conditions) {
            const val = payload[cond.field];
            switch (cond.op) {
                case 'eq':
                    if (val !== cond.value) return false;
                    break;
                case 'neq':
                    if (val === cond.value) return false;
                    break;
                case 'contains':
                    if (typeof val !== 'string' || !val.includes(cond.value)) return false;
                    break;
                default:
                    console.warn(`[AutomationService] Unknown operator: ${cond.op}`);
                    return false;
            }
        }
        return true;
    }

    static executeAction(ruleId: number, action: any, event: CRMEvent) {
        try {
            const systemUser = { id: 1, email: 'system@taskpro.local' } as any;

            switch (action.type) {
                case 'create_task': {
                    TaskService.create(systemUser, {
                        ...action.payload,
                        jobId: event.entityType === 'job' ? event.entityId : action.payload.jobId,
                        isAutoGenerated: true
                    });
                    break;
                }
                case 'send_email': {
                    CommunicationService.create({
                        channel: 'email',
                        direction: 'outbound',
                        ...action.payload,
                        jobId: event.entityType === 'job' ? event.entityId : action.payload.jobId
                    });
                    break;
                }
                case 'update_job_stage': {
                    if (event.entityType === 'job') {
                        JobService.update(systemUser, event.entityId, { stage: action.payload.stage });
                    }
                    break;
                }
                default:
                    console.warn(`[AutomationService] Unknown action type: ${action.type}`);
                    throw new Error(`Unknown action type: ${action.type}`);
            }

            AutomationService.logRun(ruleId, event.data, 'success', null);
            console.log(`[AutomationService] Executed action ${action.type} for rule ${ruleId}`);
        } catch (err: any) {
            AutomationService.logRun(ruleId, event.data, 'failed', err.message);
            throw err;
        }
    }

    static logRun(ruleId: number, payload: any, status: string, error: string | null) {
        try {
            db.prepare('INSERT INTO automation_runs (ruleId, triggerPayload, status, error) VALUES (?, ?, ?, ?)').run(
                ruleId, JSON.stringify(payload), status, error ? error.toString() : null
            );
        } catch (e) {
            console.error('[AutomationService] Failed to log run:', e);
        }
    }

    // ── CRUD for Automation Rules ──

    static getRules() {
        return db.prepare('SELECT * FROM automation_rules ORDER BY createdAt DESC').all() as AutomationRule[];
    }

    static getRule(id: number) {
        return db.prepare('SELECT * FROM automation_rules WHERE id = ?').get(id) as AutomationRule | undefined;
    }

    static createRule(user: any, data: Partial<AutomationRule>) {
        const result = db.prepare(`
            INSERT INTO automation_rules (name, description, triggerEvent, conditions, actions, isActive, ownerId)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        `).run(
            data.name,
            data.description || '',
            data.triggerEvent,
            data.conditions || '[]',
            data.actions || '[]',
            data.isActive !== undefined ? (data.isActive ? 1 : 0) : 1,
            user ? user.id : null
        );
        return AutomationService.getRule(Number(result.lastInsertRowid));
    }

    static updateRule(id: number, data: Partial<AutomationRule>) {
        const keys = Object.keys(data).filter(k => ['name', 'description', 'triggerEvent', 'conditions', 'actions', 'isActive'].includes(k));
        if (keys.length === 0) return AutomationService.getRule(id);

        const sets = keys.map(k => `${k} = ?`).join(', ');
        const values = keys.map(k => k === 'isActive' ? (data[k as keyof AutomationRule] ? 1 : 0) : data[k as keyof AutomationRule]);

        db.prepare(`UPDATE automation_rules SET ${sets}, updatedAt = CURRENT_TIMESTAMP WHERE id = ?`).run(...values, id);
        return AutomationService.getRule(id);
    }

    static deleteRule(id: number) {
        db.prepare('DELETE FROM automation_rules WHERE id = ?').run(id);
        return true;
    }
}
