import { db, queries } from '../db/index.ts';
import { validate, buildUpdate, VALID_STATUSES, VALID_PRIORITIES } from '../api/utils.ts';
import { NotFoundError, ValidationError } from '../utils/errors.ts';
import type { Task, TaskStatus, TaskPriority } from '../types.ts';
import type { User } from './UserService.ts';

export class TaskService {

    static getAll() {
        const tasks = queries.allTasks.all();
        // Enrich with subtasks and dependency info
        (tasks as any[]).forEach(t => {
            t.subtasks = queries.subtasksByTask.all(t.id);
            t.dependsOn = (queries.taskDeps.all(t.id) as any[]).map(d => d.dependsOnTaskId);
            t.isBlocked = t.dependsOn.length > 0 && t.dependsOn.some((depId: number) => {
                const dep = queries.taskStatusById.get(depId) as any;
                return dep && dep.status !== 'done';
            });
        });
        return tasks;
    }

    static getById(id: number) {
        const task = queries.taskById.get(id);
        if (!task) throw new NotFoundError(`Task with ID ${id} not found`);
        return task;
    }

    static create(user: User, data: Partial<Task>) {
        if (!data.title?.trim()) {
            throw new ValidationError('Task title is required');
        }

        const status = validate(data.status, VALID_STATUSES, 'status', 'todo') as TaskStatus;
        const priority = validate(data.priority, VALID_PRIORITIES, 'priority', 'medium') as TaskPriority;

        const result = db.prepare(`
            INSERT INTO tasks (jobId, contactId, title, description, status, priority, action, assignedTo, scheduledDate, startTime, duration, waitingOn, isAutoGenerated, ownerId, createdById)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        `).run(
            data.jobId || null,
            data.contactId || null,
            data.title,
            data.description || '',
            status,
            priority,
            data.action || 'other',
            data.assignedTo || '',
            data.scheduledDate || '',
            data.startTime || '',
            data.duration || 60,
            data.waitingOn || '',
            data.isAutoGenerated ? 1 : 0,
            user.id,
            user.id
        );

        const newId = Number(result.lastInsertRowid);
        const task = queries.taskById.get(newId);

        console.log(`[TaskService] Created task: ${data.title}`);
        return task;
    }

    static update(user: User, id: number, data: Partial<Task>) {
        const task = queries.taskById.get(id);
        if (!task) throw new NotFoundError(`Task with ID ${id} not found`);

        if (data.status) data.status = validate(data.status, VALID_STATUSES, 'status') as TaskStatus;
        if (data.priority) data.priority = validate(data.priority, VALID_PRIORITIES, 'priority') as TaskPriority;

        const updateData: any = { ...data, updatedById: user.id };
        buildUpdate('tasks', id, updateData, [
            'jobId', 'contactId', 'title', 'description', 'status', 'priority',
            'action', 'assignedTo', 'scheduledDate', 'startTime', 'duration', 'waitingOn', 'ownerId', 'updatedById'
        ]);

        return queries.taskById.get(id);
    }

    static delete(id: number) {
        const result = db.prepare('DELETE FROM tasks WHERE id = ?').run(id);
        if (result.changes === 0) {
            throw new NotFoundError(`Task with ID ${id} not found`);
        }
        return true;
    }

    // ── Subtasks ──

    static getSubtasks(taskId: number) {
        return db.prepare('SELECT * FROM subtasks WHERE taskId = ? ORDER BY createdAt ASC').all(taskId);
    }

    static createSubtask(taskId: number, title: string) {
        if (!title?.trim()) throw new ValidationError('Subtask title is required');
        const result = db.prepare('INSERT INTO subtasks (taskId, title, isCompleted) VALUES (?, ?, 0)').run(taskId, title);
        return db.prepare('SELECT * FROM subtasks WHERE id = ?').get(result.lastInsertRowid);
    }

    static updateSubtask(id: number, data: { title?: string, isCompleted?: boolean }) {
        buildUpdate('subtasks', id, data, ['title', 'isCompleted']);
        const subtask = db.prepare('SELECT * FROM subtasks WHERE id = ?').get(id);
        if (!subtask) throw new NotFoundError(`Subtask with ID ${id} not found`);
        return subtask;
    }

    static deleteSubtask(id: number) {
        const result = db.prepare('DELETE FROM subtasks WHERE id = ?').run(id);
        if (result.changes === 0) {
            throw new NotFoundError(`Subtask with ID ${id} not found`);
        }
        return true;
    }

    // ── Dependencies ──

    static addDependency(taskId: number, dependsOnTaskId: number) {
        db.prepare('INSERT OR IGNORE INTO task_dependencies (taskId, dependsOnTaskId) VALUES (?, ?)').run(taskId, dependsOnTaskId);
        return true;
    }

    static removeDependency(taskId: number, dependsOnTaskId: number) {
        db.prepare('DELETE FROM task_dependencies WHERE taskId = ? AND dependsOnTaskId = ?').run(taskId, dependsOnTaskId);
        return true;
    }
}
 
 
