import { db } from './connection.ts';

export function initializeSchema() {
    db.exec(`
    CREATE TABLE IF NOT EXISTS schema_version (
      version INTEGER PRIMARY KEY,
      appliedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      description TEXT DEFAULT ''
    );

    -- ── Jobs ──────────────────────────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS jobs (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      jobNumber TEXT NOT NULL DEFAULT '',
      name TEXT NOT NULL,
      address TEXT DEFAULT '',
      city TEXT DEFAULT '',
      state TEXT DEFAULT '',
      zip TEXT DEFAULT '',
      stage TEXT DEFAULT 'lead' CHECK(stage IN ('lead','inspection','estimate','scope_approval','contract_signed','material_order','production','supplement','final_invoice','complete','closed','canceled')),
      type TEXT DEFAULT 'residential' CHECK(type IN ('residential','commercial','insurance','retail','government','other')),
      estimatedValue REAL DEFAULT 0,
      insuranceClaim TEXT DEFAULT '',
      deductible REAL DEFAULT 0,
      assignedTo TEXT DEFAULT '',
      description TEXT DEFAULT '',
      roofType TEXT DEFAULT '',
      source TEXT DEFAULT '',
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    -- ── Contacts ──────────────────────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS contacts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      firstName TEXT NOT NULL DEFAULT '',
      lastName TEXT DEFAULT '',
      role TEXT DEFAULT 'homeowner' CHECK(role IN ('homeowner','adjuster','appraiser','subcontractor','supplier','property_manager','sales_rep','other')),
      company TEXT DEFAULT '',
      email TEXT DEFAULT '',
      phone TEXT DEFAULT '',
      address TEXT DEFAULT '',
      notes TEXT DEFAULT '',
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    -- ── Job ↔ Contact junction ────────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS job_contacts (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      jobId INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
      contactId INTEGER NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
      role TEXT DEFAULT '',
      UNIQUE(jobId, contactId)
    );

    -- ── Tasks ─────────────────────────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS tasks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      jobId INTEGER REFERENCES jobs(id) ON DELETE SET NULL,
      contactId INTEGER REFERENCES contacts(id) ON DELETE SET NULL,
      title TEXT NOT NULL,
      description TEXT DEFAULT '',
      status TEXT DEFAULT 'todo' CHECK(status IN ('todo','in_progress','waiting','done','canceled')),
      priority TEXT DEFAULT 'medium' CHECK(priority IN ('low','medium','high','critical')),
      action TEXT DEFAULT 'other',
      assignedTo TEXT DEFAULT '',
      scheduledDate TEXT DEFAULT '',
      startTime TEXT DEFAULT '',
      duration INTEGER DEFAULT 60,
      waitingOn TEXT DEFAULT '',
      isAutoGenerated INTEGER DEFAULT 0,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    -- ── Subtasks ──────────────────────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS subtasks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      taskId INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      isCompleted INTEGER DEFAULT 0,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    -- ── Task Dependencies ─────────────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS task_dependencies (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      taskId INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
      dependsOnTaskId INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(taskId, dependsOnTaskId)
    );

    -- ── Communications ────────────────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS communications (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      jobId INTEGER REFERENCES jobs(id) ON DELETE SET NULL,
      contactId INTEGER REFERENCES contacts(id) ON DELETE SET NULL,
      channel TEXT DEFAULT 'note' CHECK(channel IN ('email','call','text','meeting','note','letter')),
      direction TEXT DEFAULT 'outbound' CHECK(direction IN ('inbound','outbound')),
      subject TEXT DEFAULT '',
      body TEXT NOT NULL DEFAULT '',
      scheduledAt DATETIME,
      sentAt DATETIME,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    -- ── Documents ─────────────────────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS documents (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      jobId INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      type TEXT DEFAULT 'other',
      filePath TEXT DEFAULT '',
      fileSize INTEGER DEFAULT 0,
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    -- ── Estimates ─────────────────────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS estimates (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      jobId INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
      lineItems TEXT DEFAULT '[]',
      subtotal REAL DEFAULT 0,
      tax REAL DEFAULT 0,
      total REAL DEFAULT 0,
      status TEXT DEFAULT 'draft' CHECK(status IN ('draft','sent','approved','rejected','revised')),
      notes TEXT DEFAULT '',
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    -- ── Notes / History ───────────────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS notes (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      jobId INTEGER REFERENCES jobs(id) ON DELETE SET NULL,
      contactId INTEGER REFERENCES contacts(id) ON DELETE SET NULL,
      content TEXT NOT NULL,
      type TEXT DEFAULT 'general',
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    -- ── AI Conversation Threads ───────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS ai_threads (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL DEFAULT 'New Chat',
      summary TEXT DEFAULT '',
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
      updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );

    -- ── AI Conversation History ───────────────────────────────────────────────
    CREATE TABLE IF NOT EXISTS ai_conversations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      role TEXT NOT NULL,
      content TEXT NOT NULL,
      functionCalls TEXT DEFAULT '[]',
      threadId INTEGER REFERENCES ai_threads(id),
      createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
    );
  `);
}
 
 
