// ── CRM Core Types ──────────────────────────────────────────────────────────
// Ground-up rebuild: construction CRM modeled after AccuLynx / JobNimbus

// ── Enums ──
export type JobStage =
  | 'lead'
  | 'inspection'
  | 'estimate'
  | 'scope_approval'
  | 'contract_signed'
  | 'material_order'
  | 'production'
  | 'supplement'
  | 'final_invoice'
  | 'complete'
  | 'closed'
  | 'canceled';

export type JobType = 'residential' | 'commercial' | 'insurance' | 'retail' | 'other';
export type ContactRole = 'homeowner' | 'adjuster' | 'appraiser' | 'subcontractor' | 'supplier' | 'sales_rep' | 'project_manager' | 'other';
export type CommChannel = 'email' | 'call' | 'text' | 'meeting' | 'note' | 'letter';
export type CommDirection = 'inbound' | 'outbound';
export type TaskStatus = 'todo' | 'in_progress' | 'waiting_on' | 'done';
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';
export type TaskAction = 'inspect' | 'call' | 'email' | 'text' | 'schedule' | 'order' | 'invoice' | 'follow_up' | 'document' | 'meeting' | 'other';
export type DocType = 'photo' | 'contract' | 'estimate' | 'invoice' | 'measurement' | 'insurance' | 'permit' | 'other';
export type EstimateStatus = 'draft' | 'sent' | 'approved' | 'rejected';
export type NoteType = 'general' | 'history' | 'development' | 'bug' | 'agent';

// ── Financial Enums ──
export type ContractStatus = 'draft' | 'sent' | 'signed' | 'void';
export type InvoiceStatus = 'draft' | 'sent' | 'partial' | 'paid' | 'overdue';
export type PaymentMethod = 'credit_card' | 'ach' | 'check' | 'cash';
export type PaymentStatus = 'pending' | 'completed' | 'failed' | 'refunded';

// ── Production Enums ──
export type WorkOrderStatus = 'draft' | 'scheduled' | 'in_progress' | 'completed' | 'canceled';
export type MaterialOrderStatus = 'draft' | 'ordered' | 'delivered' | 'partial';

// ── Core Entities ──

export interface Job {
  id: number;
  jobNumber: string;        // e.g. "JOB-2026-001"
  name: string;             // homeowner name or job name
  address: string;
  city: string;
  state: string;
  zip: string;
  stage: JobStage;
  type: JobType;
  estimatedValue: number;
  insuranceClaim: string;    // claim number
  deductible: number;
  assignedTo: string;        // sales rep / PM name
  description: string;
  roofType: string;          // shingle, tile, flat, metal, etc.
  source: string;            // lead source: referral, door knock, online, etc.

  // ── Phase 7 Enrichments ──
  contractAmount?: number;
  actualCost?: number;
  amountPaid?: number;
  leadDate?: string;
  soldDate?: string;
  scheduledStartDate?: string;
  actualStartDate?: string;
  completionDate?: string;
  squareFootage?: number;
  roofPitch?: string;
  layers?: number;
  shingleColor?: string;
  trades?: string;           // JSON string of scopes
  permitNumber?: string;
  gateCode?: string;
  lockboxCode?: string;
  dumpsterLocation?: string;
  specialInstructions?: string;
  workflowTags?: string;     // JSON string of tags
  salesRepId?: number;
  projectManagerId?: number;
  crewName?: string;

  // Linked entities (populated by API)
  contacts?: JobContact[];
  tasks?: Task[];
  communications?: Communication[];
  documents?: Document[];
  estimates?: Estimate[];
  contracts?: Contract[];
  invoices?: Invoice[];
  workOrders?: WorkOrder[];
  materialOrders?: MaterialOrder[];
  checklists?: Checklist[];
  createdAt: string;
  updatedAt: string;
}

export interface Contact {
  id: number;
  firstName: string;
  lastName: string;
  role: ContactRole;
  company: string;
  email: string;
  phone: string;
  address: string;
  notes: string;
  // Linked from job_contacts
  jobs?: { jobId: number; jobName: string; role: string }[];
  createdAt: string;
}

export interface JobContact {
  id: number;
  jobId: number;
  contactId: number;
  role: string;              // role on this specific job
  contact?: Contact;         // populated by API
}

export interface Task {
  id: number;
  jobId: number | null;
  contactId: number | null;
  jobName?: string;          // populated by API
  contactName?: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  action: TaskAction;
  assignedTo: string;
  scheduledDate: string;
  startTime: string;
  duration: number;          // minutes
  waitingOn: string;
  isAutoGenerated: boolean;  // created by AI agent
  dependsOn?: number[];
  isBlocked?: boolean;
  subtasks?: Subtask[];
  createdAt: string;
  updatedAt: string;
}

export interface Communication {
  id: number;
  jobId: number | null;
  contactId: number | null;
  channel: CommChannel;
  direction: CommDirection;
  subject: string;
  body: string;
  jobName?: string;
  contactName?: string;
  scheduledAt: string | null;
  sentAt: string | null;
  // ── Phase 7 Enrichments ──
  tags?: string;             // JSON string
  attachments?: string;      // JSON array of strings
  isPinned?: boolean | number;
  // ── Phase 3 Enrichments ──
  threadId?: number | null;
  createdAt: string;
}

export interface Document {
  id: number;
  jobId: number;
  name: string;
  type: DocType;
  filePath: string;
  fileSize: number;
  jobName?: string;
  createdAt: string;
}

export interface Estimate {
  id: number;
  jobId: number;
  lineItems: string;         // JSON: [{ description, quantity, unitPrice, total }]
  subtotal: number;
  tax: number;
  total: number;
  status: EstimateStatus;
  notes: string;
  jobName?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Subtask {
  id: number;
  taskId: number;
  title: string;
  isCompleted: boolean;
  createdAt: string;
}

export interface Note {
  id: number;
  jobId: number | null;
  contactId: number | null;
  content: string;
  type: NoteType;
  createdAt: string;
}

// ── Phase 2: Workflow Automation & Audit ──

export interface AuditLog {
  id: number;
  entityType: string;
  entityId: number;
  action: string;
  actorId: number | null;
  changes: string; // JSON string
  createdAt: string;
}

export interface AutomationRule {
  id: number;
  name: string;
  description: string;
  triggerEvent: string;
  conditions: string; // JSON string
  actions: string; // JSON string
  isActive: boolean;
  ownerId: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface AutomationRun {
  id: number;
  ruleId: number;
  triggerPayload: string; // JSON string
  status: 'success' | 'failed' | 'pending';
  error: string | null;
  executedAt: string;
}

// ── Phase 3: Validated Communications ──

export interface CommunicationThread {
  id: number;
  title: string;
  jobId: number | null;
  contactId: number | null;
  status: 'open' | 'closed' | 'snoozed';
  messages?: Communication[]; // populated by API
  createdAt: string;
  updatedAt: string;
}

export interface MessageAttachment {
  id: number;
  messageId: number;
  fileName: string;
  filePath: string;
  fileSize: number;
  contentType: string;
  createdAt: string;
}

/** Generic Message Provider for SMS, Email, etc. */
export interface IMessageProvider {
  id: string;
  name: string;
  canHandle(channel: CommChannel): boolean;
  send(message: Communication): Promise<boolean>;
  receive?(): Promise<Communication[]>;
}

// ── Phase 4: Financial Workflow ──

export interface Contract {
  id: number;
  jobId: number;
  status: ContractStatus;
  totalAmount: number;
  signedAt: string | null;
  signedBy: number | null; // contactId
  pdfUrl: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Invoice {
  id: number;
  jobId: number;
  contractId: number | null;
  status: InvoiceStatus;
  amount: number;
  dueDate: string | null;
  sentAt: string | null;
  payments?: Payment[]; // populated by API
  createdAt: string;
  updatedAt: string;
}

export interface Payment {
  id: number;
  invoiceId: number;
  amount: number;
  method: PaymentMethod;
  status: PaymentStatus;
  transactionId: string | null;
  paymentDate: string | null;
  createdAt: string;
  updatedAt: string;
}

// ── Phase 5: Production & Crew Management ──

export interface Crew {
  id: number;
  name: string;
  leaderId: number | null; // contactId
  trade: string;
  color: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface WorkOrder {
  id: number;
  jobId: number;
  crewId: number | null;
  status: WorkOrderStatus;
  scheduledDate: string | null;
  instructions: string;
  completedAt: string | null;
  crew?: Crew; // populated by API
  createdAt: string;
  updatedAt: string;
}

export interface MaterialOrder {
  id: number;
  jobId: number;
  supplierId: number | null;
  status: MaterialOrderStatus;
  deliveryDate: string | null;
  materials: string; // JSON: [{ description, quantity, unit }]
  createdAt: string;
  updatedAt: string;
}

export interface ChecklistItem {
  id: string; // generated client-side or UUID
  text: string;
  isCompleted: boolean;
}

export interface Checklist {
  id: number;
  entityType: 'job' | 'work_order';
  entityId: number;
  name: string;
  items: string; // JSON: ChecklistItem[]
  createdAt: string;
  updatedAt: string;
}

// ── Phase 7: Customer / Stakeholder Portal ──

export interface PortalUser {
  id: number;
  contactId: number;
  passwordHash: string | null;
  hasAccess: boolean;
  lastLoginAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface PortalInvite {
  id: number;
  contactId: number;
  jobId: number | null;
  token: string;
  status: 'pending' | 'accepted' | 'expired';
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}

// ── Phase 9: Field / Mobile / Offline Execution ──

export type SyncAction = 'create' | 'update' | 'delete';

export interface SyncQueueItem {
  id: number;
  userId: number;
  entityType: string;
  entityId: number | null;
  localId: string | null;
  action: SyncAction;
  payload: string; // JSON string
  status: 'pending' | 'processed' | 'failed' | 'conflict';
  errorMessage: string | null;
  createdAt: string;
  processedAt: string | null;
}

// ── UI/Chat Types ──

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  actions?: {
    type: string;
    description: string;
    status: 'pending' | 'success' | 'failed';
    data?: any;
  }[];
}

// ── Job Stage Config ──
export const JOB_STAGES: { key: JobStage; label: string; color: string }[] = [
  { key: 'lead', label: 'Lead', color: '#74B9FF' },
  { key: 'inspection', label: 'Inspection', color: '#A29BFE' },
  { key: 'estimate', label: 'Estimate', color: '#FDCB6E' },
  { key: 'scope_approval', label: 'Scope Approval', color: '#FFA502' },
  { key: 'contract_signed', label: 'Contract Signed', color: '#00B894' },
  { key: 'material_order', label: 'Material Order', color: '#6C5CE7' },
  { key: 'production', label: 'Production', color: '#E17055' },
  { key: 'supplement', label: 'Supplement', color: '#FD79A8' },
  { key: 'final_invoice', label: 'Final Invoice', color: '#00CEC9' },
  { key: 'complete', label: 'Complete', color: '#2ED573' },
  { key: 'closed', label: 'Closed', color: '#636E72' },
  { key: 'canceled', label: 'Canceled', color: '#B2BEC3' },
];

export const CONTACT_ROLES: { key: ContactRole; label: string; color: string }[] = [
  { key: 'homeowner', label: 'Homeowner', color: '#6C5CE7' },
  { key: 'adjuster', label: 'Adjuster', color: '#E17055' },
  { key: 'appraiser', label: 'Appraiser', color: '#FDCB6E' },
  { key: 'subcontractor', label: 'Subcontractor', color: '#00B894' },
  { key: 'supplier', label: 'Supplier', color: '#74B9FF' },
  { key: 'sales_rep', label: 'Sales Rep', color: '#FD79A8' },
  { key: 'project_manager', label: 'Project Manager', color: '#00CEC9' },
  { key: 'other', label: 'Other', color: '#636E72' },
];
 
